site_name: Learning Notes
site_description: 学习笔记, 面试知识, Java
site_author: ydlan
theme: readthedocs
repo_url: https://github.com/ydlan/mkdocs-notes

   
extra_javascript:
  - 'js/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  
markdown_extensions:
  - pymdownx.arithmatex

nav:
- 主页: index.md

        
- 数据结构和算法:
       - 算法-复杂度分析: notes/datastructure-algorithm/algorithm-analysis.md
       - 算法-排序-总结: notes/datastructure-algorithm/sort-algorithm.md
       - 算法-排序-简单排序: notes/datastructure-algorithm/simplesort.md
       - 算法-排序-归并排序: notes/datastructure-algorithm/mergesort.md
       - 算法-排序-Shell排序: notes/datastructure-algorithm/shellsort.md
       - 算法-排序-快速排序: notes/datastructure-algorithm/quicksort.md
       - 算法-排序-基数排序: notes/datastructure-algorithm/redixsort.md
       - 算法-排序-堆排序: notes/datastructure-algorithm/heapsort.md
       - 算法-递归算法: notes/datastructure-algorithm/recursion.md 
       
       - 数据结构-栈和队列: notes/datastructure-algorithm/stack-queue.md
       - 数据结构-链表: notes/datastructure-algorithm/linklist.md
       - 数据结构-树-二叉树: notes/datastructure-algorithm/BST.md
       - 数据结构-树-红黑树: notes/datastructure-algorithm/RBTree.md
       - 数据结构-树-多叉树: notes/datastructure-algorithm/tree.md
       - 数据结构-散列: notes/datastructure-algorithm/hash.md
       - 数据结构-堆(Heap): notes/datastructure-algorithm/heap.md
       - 数据结构-图(Graph): notes/datastructure-algorithm/graph.md 
       - 数据结构-图-搜索: notes/datastructure-algorithm/dfs-bfs.md
       - 数据结构-图-应用: notes/datastructure-algorithm/graph-algorithm.md
            
- 计算机基础:
        - 基础概念-计算机导论: notes/cs-base/computer-introduction.md
        - 基础概念-计算机网络: notes/cs-base/computer-network.md
        - 基础概念-操作系统: notes/cs-base/OS-notes-concept.md
        - 基础概念-组成原理: notes/cs-base/computer-design.md
        - 基础概念-系统结构: notes/cs-base/system-structure.md
        - 基础概念-软件工程: notes/cs-base/software-engineering.md       
        - 编程语言-C语言基础: notes/language/c-notes.md
        - 编程语言-C++基础概念: notes/language/cpp-base-concept.md
        - 编程语言-C++性能优化: notes/language/optimized-cpp.md
        - 编程语言-Python编程: notes/language/python.md
        
- 程序设计(Java):
       - Java程序设计-容器类库: notes/java/java-collection.md
       - Java程序设计-关键字this和super: notes/java/java-super-this.md
       - Java程序设计-多线程基础: notes/java/java-multithreading.md
       - Java程序设计-jdbc的使用.md: notes/java/java-jdbc.md
       - Java程序设计-基础强化.md: notes/java/java-base.md
      
        
- 未分类:
        - OOP-六条设计原则: notes/oop-design.md 
        - 设计模式: notes/design-pattern.md
        






