site_name: Learning Notes
site_description: 学习笔记, 面试知识, Java
site_author: ydlan
theme: readthedocs
repo_url: https://github.com/ydlan/mkdocs-notes

   
extra_javascript:
  - 'js/extra.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  
markdown_extensions:
  - pymdownx.arithmatex

nav:
- 主页: index.md
- 面试知识:  
        - 面试要点-操作系统篇: notes/OS-notes-keynote.md
        - 面试要点-计算机网络篇: notes/computer-network-keynote.md
        
- 数据结构和算法:
       - 算法-复杂度分析: notes/datastructure-algorithm/algorithm-analysis.md
       - 算法-排序-总结: notes/datastructure-algorithm/sort-algorithm.md
       - 算法-排序-简单排序: notes/datastructure-algorithm/simplesort.md
       - 算法-排序-归并排序: notes/datastructure-algorithm/mergesort.md
       - 算法-排序-Shell排序: notes/datastructure-algorithm/shellsort.md
       - 算法-排序-快速排序: notes/datastructure-algorithm/quicksort.md
       - 算法-排序-基数排序: notes/datastructure-algorithm/redixsort.md
       - 算法-排序-堆排序: notes/datastructure-algorithm/heapsort.md
       - 算法-递归算法: notes/datastructure-algorithm/recursion.md 
       
       - 数据结构-栈和队列: notes/datastructure-algorithm/stack-queue.md
       - 数据结构-链表: notes/datastructure-algorithm/linklist.md
       - 数据结构-树-二叉树: notes/datastructure-algorithm/BST.md
       - 数据结构-树-红黑树: notes/datastructure-algorithm/RBTree.md
       - 数据结构-树-多叉树: notes/datastructure-algorithm/tree.md
       - 数据结构-散列: notes/datastructure-algorithm/hash.md
       - 数据结构-堆(Heap): notes/datastructure-algorithm/heap.md
       - 数据结构-图(Graph): notes/datastructure-algorithm/graph.md 
       - 数据结构-图-搜索: notes/datastructure-algorithm/dfs-bfs.md
       - 数据结构-图-应用: notes/datastructure-algorithm/graph-algorithm.md
            
- 知识笔记:
        - 知识笔记-操作系统-基础概念: notes/OS-notes-concept.md
        - 知识笔记-计算机网络-基础概念: notes/computer-network.md
        - 知识笔记-组成原理-基础概念: notes/computer-design.md
        - 知识笔记-系统结构-基础概念: notes/system-structure.md
        - 知识笔记-软件工程-基础概念: notes/software-engineering.md
        - 知识笔记-计算机基础-常用概念: notes/computer-introduction.md
        
- 编程语言:
       - Java程序设计-容器类库: notes/language/java/java-collection.md
       - Java程序设计-关键字this和super: notes/language/java/java-super-this.md
       - Java程序设计-多线程基础: notes/language/java/java-multithreading.md
       - Java程序设计-jdbc的使用.md: notes/language/java/java-jdbc.md
       - 编程语言-C++常用基础概念: notes/language/cpp-base-concept.md
       - 编程语言-C++性能优化指南: notes/language/optimized-cpp.md
       - 编程语言-Python编程基础: notes/language/python.md
        
- 其他: about.md







